language: objective-c
osx_image: xcode10

# xcode_project: FuelTracker.xcworkspace
# xcode_scheme: FuelTracker
# xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=FuelTracker.xcworkspace
  - APP_SCHEME="FuelTracker"
  matrix:

    - DESTINATION="OS=12.0,name=iPad Pro (9.7-inch)"     SCHEME="$APP_SCHEME"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$APP_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty;
