language: swift
osx_image: xcode10

env:
  global:
  - WORKSPACE=FuelTracker.xcworkspace
  - APP_SCHEME="FuelTracker"
  - DESTINATION="OS=12.0,name=iPhone XS"

script:
  - set -o pipefail
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$APP_SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'FuelTracker'
