language: swift
osx_image: xcode11.1
podfile: Podfile
cache: cocoapods

before_install:
 - gem install cocoapods

env:
  global:
  - WORKSPACE=FuelTracker.xcworkspace
  - APP_SCHEME="FuelTracker"
  - DESTINATION="OS=13.1,name=iPhone 8"

script:
  - set -o pipefail
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$APP_SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES clean test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'FuelTracker'
